ETAT_TRANSACTION = {
    'EN_COURS': 'EN_COURS',
    'SUCCESS': 'SUCCESS',
    'ANNULE': 'ANNULE'
}

TYPE_TRANSACTION = {
    'DEPOT': 'DEPOT',
    'RETRAIT': 'RETRAIT',
    'TRANSACTION': 'TRANSACTION'}

